---
staging:
  adapter: redshift
  host: localhost
  port: 5439
  database: bbbb_staging
  username: admin
  password: Innocycle123
  encoding: utf8
  pool: 3
  timeout: 5000
production:
  adapter: redshift
  host: localhost
  port: 5439
  database: bbbb_production
  username: admin
  password: Innocycle123
  encoding: utf8
  pool: 3
  timeout: 5000
system:
  adapter: redshift
  host: localhost
  port: 5439
  database: psw_staging
  username: admin
  password: Innocycle123
  encoding: utf8
  pool: 3
  timeout: 5000
